module.exports = {
  ROLES: {
    ISSUER: 'ISSUER',
    STUDENT: 'STUDENT'
  },

  AUDIT_ACTIONS: {
    CREDENTIAL_ISSUED: 'CREDENTIAL_ISSUED',
    CREDENTIAL_REVOKED: 'CREDENTIAL_REVOKED',
    CREDENTIAL_VERIFIED: 'CREDENTIAL_VERIFIED',
    ADMIN_CREATED: 'ADMIN_CREATED',
    ADMIN_DELETED: 'ADMIN_DELETED',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_CREATED: 'USER_CREATED',
    USER_UPDATED: 'USER_UPDATED',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED'
  },

  FILE_LIMITS: {
    MAX_SIZE: 10 * 1024 * 1024,
    ALLOWED_TYPES: ['application/pdf']
  },

  JWT_EXPIRY: '1h',

  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100
  }
};
